server:
    address: "127.0.0.1:8082"

application:
    handler: []
    allowed-host: "hbsdsrv.1337.cx"
    html-dir: "./html"
    www-dir: "./www"
    assets-dir: "./assets"

logging:
    file: ""
    level: "debug"
